<h1 align="center">Física Computacional.</h1>
<h1 align="center">Semestre 2027-1</h1>

<h2>Sergio A. Alcalá Corona </h2> 

---
### Rodrigo Vega Vilchis
### Joel Gómez Uribe
---

<h1 align="center">Programación para la física computacional</h1> 

## 1.1.4 Entrada y Salida de datos.

---
$\;$
## ENTRADA


### Obtener datos desde el usuario

Como ya hemos visto en algunos ejemplos, se puede pedir información del usuario y obtener datos insertados por el usuario directamente en la *linea de comandos* (donde se este interpretando `Python`), mediante el uso la función `input()` de la siguiente manera

In [ ]:
x = input("Ingresa el valor de x: ")
print("El valor de x es" , x)

In [ ]:
a = float(input('Dame el valor de a: '))

print("El cuadrado de a es ", a*a)

In [ ]:
temp = input("Ingresa el valor de la temperatura T: ")
T = float(temp)

print("El valor de T es" , T)

In [ ]:
y = float(input("Ingresa el valor de y: "))
print("El valor de y es",y)

Sin embargo, uno de los usos principales de Python para el cómputo científico es el de **procesar datos** generados en otro lado.

Por lo tanto, es necesario saber cómo importar y exportar archivos.

---

### Cargar arreglos desde un archivo de texto

Es posible tomar un conjunto de números guardados en un archivo de texto y convertirlos en un arreglo usando la biblioteca `loadtxt` de `numpy` de la siguiente manera:

In [1]:
import numpy as np

valores = np.loadtxt("data/valores.txt",float)
valores

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

**Nota:** Solo funciona para archivos que contengan una sola linea, con valores separadaos ya sea por una coma o un tabulador.

Así entonces podriamos calcular su promedio (*aritmetico*):

In [2]:
promedio = sum(valores)/len(valores)
print(promedio)

8.0


o el promedio de los cuadrados:

In [3]:
promedio2 = sum(valores**2)/len(valores)
print(promedio2)

82.66666666666667


Pero también podemos calcular el promedio geometrico. 

Recordemos que el promedio geometrico de $n$ valores se define como:

### $ \displaystyle \overline{x} = \displaystyle \left[ \prod_{i = 1}^n x_i \right]^{\frac{1}{n}} $

Tomando el logaritmo natural a ambos lados, tenemos:

### $ \displaystyle \ln \overline{x} = \displaystyle \ln \left[ \prod_{i = 1}^n x_i \right]^{\frac{1}{n}} = \dfrac{1}{n} \sum_{i = 1}^n \ln x_i $

de tal manera que:

### $ \displaystyle \overline{x} = \displaystyle \exp \left( \dfrac{1}{n} \sum_{i = 1}^n \ln x_i \right)$

### **Ejercicio:** 

Escribe un programa que lea el archivo `data/valores.txt` y los guarde en una arreglo de `numpy`. Calcula el promedio geometrico de dichos datos

In [23]:
import numpy as np

valores = np.loadtxt("data/valores.txt",float)
valores 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [17]:
type(valores)

numpy.ndarray

In [24]:
multiplicacion = 1 

for i in valores:
    multiplicacion = i * multiplicacion
    #print(multiplicacion)

print("El resultado de la multipicación es: ", multiplicacion)

El resultado de la multipicación es:  1307674368000.0


### Leer archivos

Para leer un archivo, primero es necesario abrirlo para leerse. Supongamos que tenemos un archivo llamado *datos.dat*, entonces lo podemos abrir para su lectura con:

In [33]:
entrada = open("data/datos.dat", "r")    # esto es un buffer

El segundo argumento, `"r"`, es para indicar que se va a leer (*“read”*) el archivo. 

El objeto `entrada` ahora representa el archivo.

Para leer del archivo abierto, hay varias posibilidades. 
Podemos leer todo de un golpe con `entrada.read()`, 

leer todo por líneas con `entrada.readlines()`, 

o línea por línea con `entrada.readline()`. 

Sin embargo, lo que se ha leído ya no se puede leer de nuevo sin cerrar el archivo con `entrada.close()` y volverlo a abrir.

Por ejemplo, podemos utilizar

In [34]:
for linea in entrada.readlines():
    print(linea)

0 	 8 

1 	 23 

2 	 48 

3 	 83 

4 	 128 

5 	 183 

6 	 248 

7 	 323 

8 	 408 

9 	 503 

10 	 608 

11 	 723 

12 	 848 

13 	 983 

14 	 1128 

15 	 1283 

16 	 1448 

17 	 1623 

18 	 1808 

19 	 2003 

20 	 2208 

21 	 2423 

22 	 2648 

23 	 2883 

24 	 3128 

25 	 3383 

26 	 3648 

27 	 3923 

28 	 4208 

29 	 4503 

30 	 4808 

31 	 5123 

32 	 5448 

33 	 5783 

34 	 6128 

35 	 6483 

36 	 6848 

37 	 7223 

38 	 7608 

39 	 8003 

40 	 8408 

41 	 8823 

42 	 9248 

43 	 9683 

44 	 10128 

45 	 10583 

46 	 11048 

47 	 11523 

48 	 12008 

49 	 12503 

50 	 13008 

51 	 13523 

52 	 14048 

53 	 14583 

54 	 15128 

55 	 15683 

56 	 16248 

57 	 16823 

58 	 17408 

59 	 18003 

60 	 18608 

61 	 19223 

62 	 19848 

63 	 20483 

64 	 21128 

65 	 21783 

66 	 22448 

67 	 23123 

68 	 23808 

69 	 24503 

70 	 25208 

71 	 25923 

72 	 26648 

73 	 27383 

74 	 28128 

75 	 28883 

76 	 29648 

77 	 30423 

78 	 31208 

79 	 32003 

80 	 32808 

81 	 33623 

82 	 34

Sin embargo, tal vez la opción más fácil e intuitiva es:

In [53]:
entrada = open("data/datos.dat", "r")    # esto es un buffer
for linea in entrada:
    print(linea)

0 	 8 

1 	 23 

2 	 48 

3 	 83 

4 	 128 

5 	 183 

6 	 248 

7 	 323 

8 	 408 

9 	 503 

10 	 608 

11 	 723 

12 	 848 

13 	 983 

14 	 1128 

15 	 1283 

16 	 1448 

17 	 1623 

18 	 1808 

19 	 2003 

20 	 2208 

21 	 2423 

22 	 2648 

23 	 2883 

24 	 3128 

25 	 3383 

26 	 3648 

27 	 3923 

28 	 4208 

29 	 4503 

30 	 4808 

31 	 5123 

32 	 5448 

33 	 5783 

34 	 6128 

35 	 6483 

36 	 6848 

37 	 7223 

38 	 7608 

39 	 8003 

40 	 8408 

41 	 8823 

42 	 9248 

43 	 9683 

44 	 10128 

45 	 10583 

46 	 11048 

47 	 11523 

48 	 12008 

49 	 12503 

50 	 13008 

51 	 13523 

52 	 14048 

53 	 14583 

54 	 15128 

55 	 15683 

56 	 16248 

57 	 16823 

58 	 17408 

59 	 18003 

60 	 18608 

61 	 19223 

62 	 19848 

63 	 20483 

64 	 21128 

65 	 21783 

66 	 22448 

67 	 23123 

68 	 23808 

69 	 24503 

70 	 25208 

71 	 25923 

72 	 26648 

73 	 27383 

74 	 28128 

75 	 28883 

76 	 29648 

77 	 30423 

78 	 31208 

79 	 32003 

80 	 32808 

81 	 33623 

82 	 34

Es decir, el archivo ¡se comporta como una secuencia!

Ahora bien, la línea viene como una sola cadena, con espacios etc. Para extraer la información, primero necesitamos dividirlo en palabras:

In [54]:
palabras = linea.split()
print(palabras)

['99', '50003']


Si todos los datos en realidad son números, entonces tenemos que procesar cada palabra, convirtiéndola en un número:

In [51]:
datos = []
for i in palabras:
    datos.append(float(i))

print(datos)

[99.0, 50003.0]


Resulta que hay una manera más fácil, de más alto nivel y más rápida de hacer esto:

In [58]:
m = map(float, palabras)
print(palabras)
m 

['99', '50003']


Eso literalmente mapea la función float sobre la lista palabras.

Combinando todo, podemos escribir:

In [44]:
entrada = open("data/datos.dat", "r")

for linea in entrada:
    datos = map(float, linea.split())

print(datos)

Y ya dentro del bucle podemos manipular los datos como queramos.

### **Ejercicio:** 

Escribe un programa que lea el archivo `datos.dat` y guarde en una arreglo de `numpy` los datos de la primera columna y en otro diferente los datos de la segunda columna.

In [45]:
entrada = open("data/datos.dat", "r")   # Leer datos  
datos_array = [] #CRear una lista vacía 
for linea in entrada:
    palabra = linea.split() # # Guarda una 
    datos_array.append(palabra)

In [46]:
datos_totales = [[],[]]
for i in datos_array:
    datos_array_1 = float(i[0])
    datos_totales[0].append(datos_array_1)
    datos_array_2 = float(i[1])
    datos_totales[1].append(datos_array_2)
    

In [47]:
np_arreglo = np.array(datos_totales)
np_arreglo[1]

array([8.0000e+00, 2.3000e+01, 4.8000e+01, 8.3000e+01, 1.2800e+02,
       1.8300e+02, 2.4800e+02, 3.2300e+02, 4.0800e+02, 5.0300e+02,
       6.0800e+02, 7.2300e+02, 8.4800e+02, 9.8300e+02, 1.1280e+03,
       1.2830e+03, 1.4480e+03, 1.6230e+03, 1.8080e+03, 2.0030e+03,
       2.2080e+03, 2.4230e+03, 2.6480e+03, 2.8830e+03, 3.1280e+03,
       3.3830e+03, 3.6480e+03, 3.9230e+03, 4.2080e+03, 4.5030e+03,
       4.8080e+03, 5.1230e+03, 5.4480e+03, 5.7830e+03, 6.1280e+03,
       6.4830e+03, 6.8480e+03, 7.2230e+03, 7.6080e+03, 8.0030e+03,
       8.4080e+03, 8.8230e+03, 9.2480e+03, 9.6830e+03, 1.0128e+04,
       1.0583e+04, 1.1048e+04, 1.1523e+04, 1.2008e+04, 1.2503e+04,
       1.3008e+04, 1.3523e+04, 1.4048e+04, 1.4583e+04, 1.5128e+04,
       1.5683e+04, 1.6248e+04, 1.6823e+04, 1.7408e+04, 1.8003e+04,
       1.8608e+04, 1.9223e+04, 1.9848e+04, 2.0483e+04, 2.1128e+04,
       2.1783e+04, 2.2448e+04, 2.3123e+04, 2.3808e+04, 2.4503e+04,
       2.5208e+04, 2.5923e+04, 2.6648e+04, 2.7383e+04, 2.8128e

Ejercicio mejorado usando map 

In [59]:
entrada = open("data/datos.dat", "r")    # esto es un buffer
datos = [[], []]
for linea in entrada:
    #print(linea)
    palabras = linea.split()
    palabras = list(map(float, palabras))
    for j in range(len(palabras)):
        datos[j].append(palabras[j])

    #print(palabras)
datos = np.array(datos)

### SALIDA

Como ya hemos visto en el *interprete de comandos python*, en *ipython* o *Jupyter*, para mandar un resultado a la salida simplemente hay que definirlo y después escribirlo y presionar enter.

In [ ]:
a = 17.3
a

In [ ]:
b = "hola"
b

Adicionalmente se puede utilizar el comando `print()`

In [ ]:
print("imprimiendo datos", a, b)

### Escribir archivos

Para mandar las salida del programa a un archivo (escribir), también se usa el comando `open()`; pero para este caso hay que generar un *`buffer`* de escritura, especificando se sera de escritura:

`open("archoDeEscritura.dat",`**`"w"`**`)`

Para hacer eso, necesitamos poder abrir un archivo para escribirse:

In [ ]:
salida = open("resultados.dat", "w")  # Esto es un buffer de salida

La parte más complicada viene al momento de escribir en el archivo. Para hacerlo, ocupamos la función:

`salida.write()`

Sin embargo, esta función puede escribir solamente cadenas. Por lo tanto, si queremos escribir números contenidos en variables, es necesario convertirlos primero a la forma de cadena.

Una manera de hacer eso es con la función str(), y concatenar (juntar) distintas cadenas con +:



In [ ]:
a = 3
s = "El valor de a es " + str(a)

print(s)

Sin embargo, para largas secuencias de datos eso se vuelve latoso.

La manera más elegante de hacerlo es con la sustitución de variables en cadenas . En una cadena ponemos una secuencia especial de caracteres, empezando por `%`, que indica que se sustituirá el valor de una variable:

In [ ]:
a = 3
s = "El valor de a es %d" % a

b = 3.5; c = 10.1
s = "b = %g; c = %g" % (b, c)

El carácter después del `%` indica el tipo de variable que incluir en la cadena: 

- **`d`** corresponde a un _**entero**_, 


- **`g`**  o **`f`**  a un _**flotante**_ y 


- **`s`**  a _**otra cadena**_.


Finalmente ahora podemos imprimir en el archivo, por ejemplo:

In [ ]:
salida.write(" %g\t %g" % (a,b) )

Aquí, **`\t`** representa un tabulador, y **`\n`** una nueva línea.

#### Ejemplo

In [ ]:
def fibonacci(n):
    
    output = []
    
    f1,f2 = 1,1

    while f2 < n:
        output.append(f2)        
        f1,f2 = f2,f1+f2
    
    return output


In [ ]:
fibo = fibonacci(100)

outputBuff = open("fibonacci.dat", "w")

for n in fibo:
    outputBuff.write("%d \n" % n)
#     outputBuff.write("%f \n" % n)

outputBuff.close()

In [ ]:
fibo2 = fibonacci(1000)

with open("fibonacci2.dat", 'a') as out:
    for n in fibo2:
        out.write(str(n) + '\n')

### **Ejercicio:** 

Usando los arreglos de `numpy` del ejercicio anterior, que contienen los datos recolectados del archivo `data/datos.dat`; escribe un programa que escriba **dos archivos de texto diferentes**, que guarden los datos de cada arreglo.

## Scripts de Python.

Una vez que las secuencias de comandos se complican, podría pasar que queramos repetir la misma secuencia varias veces o bien reusar algunas secuencias de comandos, sin embargo esto significaría reescribir todo nuevamente en el interprete de comandos, o estar editando y volviendo a correr las celdas en *Jupyter*.

Entonces sería conveniente poder guardar bloques de instrucciones completos y correrlos de una sola vez.
Esto es posible realizando un *programa*, o _**script**_. 

Esto consiste en un **archivo de texto**, cuyo nombre termina en **.py**, en el cual se escribe y guarda la secuencia de comandos.

Por ejemplo, consideremos el siguiente código: 

In [ ]:
from fractions import Fraction

a = Fraction(3, 5)
b = Fraction(1)
c = a + b
d = Fraction(4, 6)
d 
e = a + d
print(a,b,c,d,e)

podemos escribirlo en un editor de textos y salvarlo como un archivo cuad.py. Y así entonces podemos correr el código desde **ipython** o _**Jupyter Notebook**_, de la siguiente manera:

In [ ]:
run cuad.py

**Nota:** si no estamos en el mismo directorio donde se guardo el archivo script.py, habrá que especificar la ruta relativa o absoluta según sea el caso.

Alternativamente, podemos tratar el script como un *programa* en sí, y **ejecutarlo desde la consola**:

**`$>`**`python cuad.py`

Aunque no hay una forma rígida de programar, para escribir un buen script (programa) se puede seguir la siguiente estructura:

- `Comentarios generales del programa`


- `Importar bibliotecas (librerías o módulos)`


- `Definir funciones`


- `Definir variables globales`


- `Comandos de entrada por parte del usuario (si es necesario)`


- `Estructuras de control y/o cálculos`


- `Comandos de salida (si es necesario)`

Finalmente, es posible exportar los _**Cuadernos de Jupyter**_, como **scripts**, desde el menu *File*.
Intentalo ...